- type: entity
  id: MaterialReclaimerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: material reclaimer machine board
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: MaterialReclaimer
      stackRequirements:
        Manipulator: 2
        Steel: 5
        Plastic: 5
