using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Content.Shared.Roles;
using Content.Shared.Preferences;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;

namespace Content.Client._Maid.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CharacterPreferencesWidget : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;

        private static readonly Regex TitleCaseRegex = new Regex(@"\b(\w)(\w*)\b", RegexOptions.Compiled);

        public CharacterPreferencesWidget()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();

            _preferencesManager.OnServerDataLoaded += RefreshWidget;
            _preferencesManager.OnPreferencesUpdated += RefreshWidget;


            if (_preferencesManager.ServerDataLoaded)
                RefreshWidget();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();

            _preferencesManager.OnServerDataLoaded -= RefreshWidget;
            _preferencesManager.OnPreferencesUpdated -= RefreshWidget;
        }

        private void RefreshWidget()
        {
            RefreshAntagGrid();
            RefreshHighPriorityJob();
        }

        private void RefreshAntagGrid()
        {
            AntagGridContainer.DisposeAllChildren();

            var profile = _preferencesManager.Preferences?.SelectedCharacter as HumanoidCharacterProfile;
            if (profile == null)
                return;

            var antags = _prototypeManager.EnumeratePrototypes<AntagPrototype>()
                .Where(a => a.SetPreference)
                .OrderBy(a => Loc.GetString(a.Name))
                .ToList();

            if (!antags.Any())
                return;

            var grid = new GridContainer { Rows = 2, HorizontalExpand = true };

            foreach (var antag in antags)
            {
                var enabled = profile.AntagPreferences.Contains(antag.ID);

                var outer = new PanelContainer
                {
                    MinSize = new Vector2(37, 37),
                    MaxSize = new Vector2(37, 37),
                    HorizontalExpand = false,
                    VerticalExpand = false,
                };

                outer.PanelOverride = new StyleBoxFlat
                {
                    BorderColor = enabled ? Color.Green : Color.Transparent,
                    BorderThickness = new Thickness(3),
                    BackgroundColor = Color.Transparent,
                };

                var btn = new TextureButton
                {
                    Modulate = enabled ?  Color.White : Color.Gray,
                    MinSize = new Vector2(32, 32),
                    MaxSize = new Vector2(32, 32),
                    ToolTip = Loc.GetString(antag.Name),
                    HorizontalExpand = false,
                    VerticalExpand = false,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                };

                btn.TexturePath = "/Textures/_Maid/Interface/AntagIcons/" + antag.ID.ToLower() + ".png";

                outer.AddChild(btn);
                grid.AddChild(outer);
            }

            AntagGridContainer.AddChild(grid);
        }

        private void RefreshHighPriorityJob()
        {
            HighPriorityJobContainer.DisposeAllChildren();

            var profile = _preferencesManager.Preferences?.SelectedCharacter as HumanoidCharacterProfile;
            if (profile == null)
            {
                HighPriorityJobContainer.AddChild(new Label
                {
                    Text = Loc.GetString("character-preference-no-high-priority-job"),
                    StyleClasses = { "LabelBig" },
                    VerticalAlignment = VAlignment.Center,
                });
                return;
            }

            var highJobId = profile.JobPriorities.FirstOrDefault(kv => kv.Value == JobPriority.High).Key;
            if (highJobId == default)
            {
                HighPriorityJobContainer.AddChild(new Label
                {
                    Text = Loc.GetString("character-preference-no-high-priority-job"),
                    StyleClasses = { "LabelBig" },
                    VerticalAlignment = VAlignment.Center,
                });
                return;
            }

            if (!_prototypeManager.TryIndex(highJobId, out var job))
            {
                HighPriorityJobContainer.AddChild(new Label
                {
                    Text = Loc.GetString("character-preference-unknown-job"),
                    StyleClasses = { "LabelBig" },
                    VerticalAlignment = VAlignment.Center,
                });
                return;
            }

            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };

            var iconContainer = new PanelContainer
            {
                MinSize = new Vector2(32, 32),
                MaxSize = new Vector2(32, 32),
                ToolTip = job.LocalizedName,
            };

            iconContainer.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = Color.Transparent,
                BorderThickness = new Thickness(0),
            };

            var icon = new TextureRect
            {
                TextureScale = new Vector2(3.75f, 3.75f),
                VerticalAlignment = VAlignment.Center,
            };

            var jobIconProto = _prototypeManager.Index(job.Icon);

            icon.Texture = _entityManager.System<SpriteSystem>().Frame0(jobIconProto.Icon);

            iconContainer.AddChild(icon);
            box.AddChild(iconContainer);

            var nameLabel = new Label
            {
                Text = TitleCaseRegex.Replace(Loc.GetString(job.Name),
                    m => m.Groups[1].Value.ToUpper() + m.Groups[2].Value),
                StyleClasses = { "LabelBig" },
                VerticalAlignment = VAlignment.Center,
            };
            box.AddChild(nameLabel);

            HighPriorityJobContainer.AddChild(box);

        }
    }
}
